//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Turnierverwaltung
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public int? GamePk { get; set; }
        public int HomeClubFk { get; set; }
        public int GuestClubFk { get; set; }
        public Nullable<int> HomeResult { get; set; }
        public Nullable<int> GuestResult { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string StrDateTime => $"{DateTime:d}";
        public bool Played { get; set; }
        public Nullable<int> RefereeFk { get; set; }
    
        public virtual Club Club { get; set; }
        public virtual Club Club1 { get; set; }
        public virtual Referee Referee { get; set; }
        public virtual Referee Referee1 { get; set; }
    }
}
